import Head from "next/head";
import React from "react";
import Header from "./Header";
// import styles from "../styles/Home.module.css";
import styles from "../styles/Layout.module.css";
import Footer from "./Footer";

export default function Layout(props) {
  return (
    <div role="main">
      <Head>
        <title>Tupulung event planner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/webFavicon.png" />
      </Head>
      <Header />
      <div className="layoutContainer bg-neutral-100 dark:bg-slate-800">
        <main className="" id={styles["layoutSubcom"]}>
          {props.children}
        </main>
      </div>
      <Footer />
    </div>
  );
}
